# -*- coding: utf-8 -*-
"""PDF_CLIENT_NOISE_REMOVAL.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13R0V0DyN3LpimjjFDFIVD1nOE9R5WOUy
"""

# Commented out IPython magic to ensure Python compatibility.
# =====================================================================
# CELL 1: INSTALL & IMPORT LIBRARIES
# =====================================================================
# Run this cell FIRST. It installs the packages and imports them.
# =====================================================================

# Install the required libraries inside your Jupyter environment


import os          # For file path operations (checking if file exists, getting file size)
import time        # For measuring how long the processing takes
import numpy as np # NumPy: for numerical array operations
import cv2         # OpenCV: for image processing
import fitz        # PyMuPDF (fitz): reads/writes PDF files and renders pages

# Matplotlib: used to display images side-by-side inside Jupyter Notebook
# %matplotlib inline
import matplotlib.pyplot as plt

print("✅ All libraries imported successfully!")
print(f"   OpenCV version: {cv2.__version__}")
print(f"   PyMuPDF version: {fitz.__doc__}")

# =====================================================================
# CELL 2: CONFIGURE YOUR PDF PATHS
# =====================================================================
# Change INPUT_PDF to your uploaded file name.
# Change OUTPUT_PDF to the name you want for the cleaned file.
# =====================================================================

# ── YOUR INPUT PDF (the noisy file in your Jupyter folder) ──
INPUT_PDF = r"SC0496.PDF"

# ── YOUR OUTPUT PDF (where the cleaned result will be saved) ──
OUTPUT_PDF = r"SC0496_Cleanest.pdf"

# ── PAGE RANGE FOR PROCESSING ──
# Start with a small range (1 to 5) for quick testing.
# Set END_PAGE = None when you are ready to process all pages.
START_PAGE = 1
END_PAGE = 59        # Set to None for the full PDF

# ── QUALITY SETTINGS ──
DPI = 290            # 300 DPI is ideal for preserving sharp text quality

# ── Verify the input file exists ──
if os.path.exists(INPUT_PDF):
    size_mb = os.path.getsize(INPUT_PDF) / (1024 * 1024)
    print(f"✅ Input PDF found: {INPUT_PDF}")
    print(f"   File size: {size_mb:.2f} MB")
else:
    print(f"❌ ERROR: File '{INPUT_PDF}' not found in this folder.")
    print(f"   Please check the spelling or upload the file.")

# =====================================================================
# CELL 3: THE CLEANING ALGORITHM (With Individual Edge Controls)
# =====================================================================
# You can fine-tune individual sides (Top, Bottom, Left, Right) here.
# To protect headers/footers, reduce top and bottom values.
# =====================================================================

def clean_page_image(img, block_size=31, c_val=15, bilateral_d=9,

                     # ─── 1. ABSOLUTE BORDER CROP (Forces edge strips to pure white) ───
                     margin_top_pct    = 0.000,  # Set to 0.0 to completely protect top headers
                     margin_bottom_pct = 0.000,  # Set to 0.0 to completely protect bottom footers
                     margin_left_pct   = 0.010,  # Left side crop (2%)
                     margin_right_pct  = 0.026,  # Right side crop (2%)

                     # ─── 2. SMART CLEANUP ZONES (Inspects outer margins for scanning noise) ───
                     smart_top_pct    = 0.020,  # Only inspect top 2% (reduced to protect headers)
                     smart_bottom_pct = 0.020,  # Only inspect bottom 2% (reduced to protect page numbers)
                     smart_left_pct   = 0.050,  # Inspect outer 10% of left side
                     smart_right_pct  = 0.065   # Inspect outer 10% of right side
                    ):
    """
    Cleans a page image with independent margin controls for each edge.
    """
    h, w = img.shape[:2]

    # 1. Convert to grayscale
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

    # 2. Apply bilateral filter to smooth paper noise but keep text edges sharp
    if bilateral_d > 0:
        smoothed = cv2.bilateralFilter(gray, d=bilateral_d, sigmaColor=75, sigmaSpace=75)
    else:
        smoothed = gray

    # 3. Adaptive thresholding
    thresh = cv2.adaptiveThreshold(
        smoothed,
        255,
        cv2.ADAPTIVE_THRESH_GAUSSIAN_C,
        cv2.THRESH_BINARY,
        block_size,
        c_val
    )

    # 4. Clean Borders and Edge Shadows
    # 4a. Clear absolute outer margins (with individual top/bottom/left/right controls)
    my_top    = int(h * margin_top_pct)
    my_bottom = int(h * margin_bottom_pct)
    mx_left   = int(w * margin_left_pct)
    mx_right  = int(w * margin_right_pct)

    if my_top > 0:
        thresh[0:my_top, :] = 255
    if my_bottom > 0:
        thresh[h-my_bottom:h, :] = 255
    if mx_left > 0:
        thresh[:, 0:mx_left] = 255
    if mx_right > 0:
        thresh[:, w-mx_right:w] = 255

    # 4b. Smart edge shadow removal using connected components
    inverted = cv2.bitwise_not(thresh)
    num_labels, labels, stats, centroids = cv2.connectedComponentsWithStats(inverted, connectivity=8)

    # Define margin boundaries based on individual side percentages
    bx_left   = int(w * smart_left_pct)
    bx_right  = int(w * smart_right_pct)
    by_top    = int(h * smart_top_pct)
    by_bottom = int(h * smart_bottom_pct)

    for label in range(1, num_labels):
        left = stats[label, cv2.CC_STAT_LEFT]
        top = stats[label, cv2.CC_STAT_TOP]
        width = stats[label, cv2.CC_STAT_WIDTH]
        height = stats[label, cv2.CC_STAT_HEIGHT]
        area = stats[label, cv2.CC_STAT_AREA]

        right = left + width
        bottom = top + height

        # 1. Check if the component is COMPLETELY within the outer margins
        is_in_left_margin   = right < bx_left
        is_in_right_margin  = left > (w - bx_right)
        is_in_top_margin    = bottom < by_top
        is_in_bottom_margin = top > (h - by_bottom)

        if is_in_left_margin or is_in_right_margin or is_in_top_margin or is_in_bottom_margin:
            # Erase it if it matches small/medium noise sizes
            if area < (w * h) * 0.02 or (width < w * 0.08 and height < h * 0.08):
                thresh[labels == label] = 255
                continue

        # 2. Check if the component touches or is very close to the edge
        near_left   = left < bx_left
        near_right  = right > (w - bx_right)
        near_top    = top < by_top
        near_bottom = bottom > (h - by_bottom)

        if near_left or near_right or near_top or near_bottom:
            touches_edge = (left <= 2) or (right >= w - 2) or (top <= 2) or (bottom >= h - 2)

            is_noise = False
            if touches_edge:
                # If touching boundary, erase if it is medium size or larger
                if width > w * 0.03 or height > h * 0.03 or area > 300:
                    is_noise = True
            else:
                # Near the edge but not touching - erase large spine/gutter shadow blobs
                if area > 1000 or width > w * 0.06 or height > h * 0.06:
                    is_noise = True

            if is_noise:
                thresh[labels == label] = 255

    return thresh

print("✅ Updated cleaning algorithm with individual side controls defined!")

# =====================================================================
# CELL 4: THE PDF PIPELINE
# =====================================================================
# Reads the original PDF, processes each page, and builds output PDF.
# =====================================================================

def clean_pdf(input_path, output_path, start_page=1, end_page=None, dpi=300):
    print(f"📖 Opening: {input_path}")
    doc = fitz.open(input_path)
    total_pages = len(doc)

    start_idx = max(0, start_page - 1)
    end_idx = min(total_pages, end_page if end_page is not None else total_pages)
    num_pages = end_idx - start_idx

    print(f"   Total pages in PDF: {total_pages}")
    print(f"   Processing: page {start_idx + 1} to {end_idx} ({num_pages} pages)")
    print(f"   Resolution: {dpi} DPI")
    print("─" * 50)

    out_doc = fitz.open()
    zoom = dpi / 72.0
    matrix = fitz.Matrix(zoom, zoom)
    t_start = time.time()

    for idx in range(start_idx, end_idx):
        page_num = idx + 1
        t_page = time.time()

        page = doc[idx]
        pix = page.get_pixmap(matrix=matrix)
        img = np.frombuffer(pix.samples, dtype=np.uint8).reshape(pix.h, pix.w, pix.n)

        if pix.n == 3:
            img = cv2.cvtColor(img, cv2.COLOR_RGB2BGR)
        elif pix.n == 4:
            img = cv2.cvtColor(img, cv2.COLOR_RGBA2BGRA)
        elif pix.n == 1:
            img = cv2.cvtColor(img, cv2.COLOR_GRAY2BGR)

        # Clean using Cell 3 function
        cleaned = clean_page_image(img)

        # Encode as PNG to preserve exact lossless quality
        ok, buf = cv2.imencode(".png", cleaned)
        if not ok:
            print(f"   ⚠️  Page {page_num}: encoding failed, skipping")
            continue

        rect = page.rect
        out_page = out_doc.new_page(width=rect.width, height=rect.height)
        out_page.insert_image(rect, stream=buf.tobytes())

        print(f"   ✅ Page {page_num}/{total_pages} done ({time.time()-t_page:.2f}s)")

    print("─" * 50)
    print(f"💾 Saving cleaned PDF to: {output_path}")

    out_doc.save(output_path, garbage=3, deflate=True)
    out_doc.close()
    doc.close()

    total_time = time.time() - t_start
    in_size = os.path.getsize(input_path) / (1024 * 1024)
    out_size = os.path.getsize(output_path) / (1024 * 1024)
    reduction = (1 - out_size / in_size) * 100

    print()
    print("═" * 50)
    print("📊 SUMMARY")
    print("═" * 50)
    print(f"   Pages processed:  {num_pages}")
    print(f"   Total time:       {total_time:.1f} seconds")
    print(f"   Speed:            {num_pages / total_time:.1f} pages/second")
    print(f"   Input file size:  {in_size:.2f} MB")
    print(f"   Output file size: {out_size:.2f} MB")
    print(f"   Compression:      {reduction:.1f}% reduction")
    print("═" * 50)

print("✅ PDF pipeline defined successfully!")

# =====================================================================
# CELL 5: RUN THE CLEANING
# =====================================================================

clean_pdf(
    input_path  = INPUT_PDF,     # from Cell 2
    output_path = OUTPUT_PDF,    # from Cell 2
    start_page  = START_PAGE,    # from Cell 2
    end_page    = END_PAGE,      # from Cell 2 (None = all pages)
    dpi         = DPI            # from Cell 2 (300 recommended)
)

# =====================================================================
# CELL 7: GENERATE PARALLEL COMPARISON PDF (Side-by-Side)
# =====================================================================
# This cell is completely self-contained. It will run successfully
# even if your notebook kernel was restarted.
# =====================================================================

# ─── 1. CONFIGURE PAGE RANGE FOR COMPARISON PDF ───
START_PAGE_COMP = 1       # First page to include in comparison
END_PAGE_COMP   = 59      # Last page to include (None = process all pages)

# ─── 2. CONFIGURE FILE NAMES ───
INPUT_FILENAME      = "SC0496.PDF"                # Your noisy original PDF
OUTPUT_FILENAME     = "SC0496_Cleanest.pdf"       # Your cleaned PDF
COMPARISON_FILENAME = "SC0496_Comparison_Cleanest.pdf" # Output comparison PDF

# ─── 3. RESOLUTION SETTINGS ───
# 150/200 DPI keeps file sizes small and downloads fast.
# Change to 300 DPI if you want absolute max print-quality.
COMPARE_DPI = 300

# ─── 4. PATH RESOLUTION (NameError Fix) ───
CURRENT_FOLDER = os.getcwd()
INPUT_PDF      = os.path.join(CURRENT_FOLDER, INPUT_FILENAME)
OUTPUT_PDF     = os.path.join(CURRENT_FOLDER, OUTPUT_FILENAME)
COMPARISON_PDF = os.path.join(CURRENT_FOLDER, COMPARISON_FILENAME)

# ─── 5. GENERATION PROCESS ───
# Verify files exist before opening
if not os.path.exists(INPUT_PDF):
    raise FileNotFoundError(f"Original PDF not found at: {INPUT_PDF}")
if not os.path.exists(OUTPUT_PDF):
    raise FileNotFoundError(f"Cleaned PDF not found at: {OUTPUT_PDF}. Please run Cell 5 first to clean your PDF.")

print(f"📖 Opening: {INPUT_PDF}")
doc_orig = fitz.open(INPUT_PDF)
doc_clean = fitz.open(OUTPUT_PDF)

total_orig = len(doc_orig)
total_clean = len(doc_clean)
total_pages = min(total_orig, total_clean)

# Calculate page range index (0-indexed)
start_idx = max(0, START_PAGE_COMP - 1)
end_idx = min(total_pages, END_PAGE_COMP if END_PAGE_COMP is not None else total_pages)
num_pages = end_idx - start_idx

print(f"   Original PDF: {total_orig} pages")
print(f"   Cleaned PDF:  {total_clean} pages")
print(f"   Creating comparison PDF for pages {start_idx+1} to {end_idx} ({num_pages} pages)...")
print("─" * 50)

# Create a blank PDF for side-by-side pages
doc_compare = fitz.open()

zoom = COMPARE_DPI / 72.0
matrix = fitz.Matrix(zoom, zoom)
t_start = time.time()

for idx in range(start_idx, end_idx):
    page_num = idx + 1
    t_page = time.time()

    # Render the original page (Keep original color/RGB)
    page_o = doc_orig[idx]
    pix_o = page_o.get_pixmap(matrix=matrix)
    img_orig = np.frombuffer(pix_o.samples, dtype=np.uint8).reshape(pix_o.h, pix_o.w, pix_o.n)

    if pix_o.n == 3:
        img_orig = cv2.cvtColor(img_orig, cv2.COLOR_RGB2BGR)
    elif pix_o.n == 4:
        img_orig = cv2.cvtColor(img_orig, cv2.COLOR_RGBA2BGR)
    elif pix_o.n == 1:
        img_orig = cv2.cvtColor(img_orig, cv2.COLOR_GRAY2BGR)

    # Render the cleaned page (Keep original color/RGB)
    page_c = doc_clean[idx]
    pix_c = page_c.get_pixmap(matrix=matrix)
    img_clean = np.frombuffer(pix_c.samples, dtype=np.uint8).reshape(pix_c.h, pix_c.w, pix_c.n)

    if pix_c.n == 3:
        img_clean = cv2.cvtColor(img_clean, cv2.COLOR_RGB2BGR)
    elif pix_c.n == 4:
        img_clean = cv2.cvtColor(img_clean, cv2.COLOR_RGBA2BGR)
    elif pix_c.n == 1:
        img_clean = cv2.cvtColor(img_clean, cv2.COLOR_GRAY2BGR)

    # Match heights if they differ slightly
    h_orig, w_orig = img_orig.shape[:2]
    h_clean, w_clean = img_clean.shape[:2]
    if h_orig != h_clean:
        new_w = int(w_clean * h_orig / h_clean)
        img_clean = cv2.resize(img_clean, (new_w, h_orig), interpolation=cv2.INTER_CUBIC)

    # Combine side-by-side (Original on left, Cleaned on right)
    combined = np.hstack((img_orig, img_clean))

    # Encode as lossless PNG
    ok, buf = cv2.imencode(".png", combined)
    if not ok:
        print(f"   ⚠️ Page {page_num}: failed to encode comparison")
        continue

    # Calculate page dimensions in PDF points
    combined_h, combined_w = combined.shape[:2]
    page_w_pts = combined_w * 72.0 / COMPARE_DPI
    page_h_pts = combined_h * 72.0 / COMPARE_DPI

    # Create comparison page and insert the side-by-side image
    compare_page = doc_compare.new_page(width=page_w_pts, height=page_h_pts)
    target_rect = fitz.Rect(0, 0, page_w_pts, page_h_pts)
    compare_page.insert_image(target_rect, stream=buf.tobytes())

    print(f"   ✅ Page {page_num}/{total_pages} comparison created ({time.time()-t_page:.2f}s)")

# Save the final comparison PDF
print("─" * 50)
print(f"💾 Saving comparison PDF to: {COMPARISON_PDF}")
doc_compare.save(COMPARISON_PDF, garbage=3, deflate=True)
doc_compare.close()
doc_orig.close()
doc_clean.close()

elapsed = time.time() - t_start
file_size = os.path.getsize(COMPARISON_PDF) / (1024 * 1024)
print(f"🎉 Success! Comparison PDF saved as '{COMPARISON_FILENAME}' ({file_size:.2f} MB) in {elapsed:.1f}s.")









